### PR TITLE
readme.md updated 

### PR DESCRIPTION
**Pull request by aschkun**
it's a demo version

### CODE REVIEW

**Review by Gartham — COMMENTED** [review]
This template looks good so far!

**Comment by aschkun** [comment]
add it to the main branch so that i can how it looks afterall

**Comment by Gartham** [comment]
I would but I think it would be better if it were completed all the way through first.

We can see how it would look on the fork though. Check this page: https://github.com/aschkun/c10ver

**Comment by aschkun** [comment]
ok sure but it will take a while is it ok

**Comment by Gartham** [comment]
Yeah, that's fine! Tell me if you need any help.

**Pull request merged**
